# Copyright 2019 Contributors to Hyperledger Sawtooth
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------------


version: "3"

networks:
  node_network:
    driver: overlay

services:
  shell:
    image: hyperledger/sawtooth-shell:1.0
    depends_on:
      - rest-api-0
      - rest-api-1
      - rest-api-2
      - rest-api-3
    networks:
      - node_network

  rest-api-1:
    image: hyperledger/sawtooth-rest-api:1.0
    deploy:
      placement:
        constraints: [node.hostname == node-nuc1]
    expose:
      - 8008
    depends_on:
      - validator-1
    networks:
      - node_network
    command: sawtooth-rest-api --connect tcp://validator-1:4004 --bind rest-api-1:8008 -vv

  rest-api-2:
    image: hyperledger/sawtooth-rest-api:1.0
    deploy:
      placement:
        constraints: [node.hostname == node-nuc2]
    expose:
      - 8008
    depends_on:
      - validator-2
    networks:
      - node_network
    command: sawtooth-rest-api --connect tcp://validator-2:4004 --bind rest-api-2:8008 -vvv

  rest-api-3:
    image: hyperledger/sawtooth-rest-api:1.0
    deploy:
      placement:
        constraints: [node.hostname == node-nuc3]
    expose:
      - 8008
    depends_on:
      - validator-3
    networks:
      - node_network
    command: sawtooth-rest-api --connect tcp://validator-3:4004 --bind rest-api-3:8008 -vv

  rest-api-4:
    image: hyperledger/sawtooth-rest-api:1.0
    deploy:
      placement:
        constraints: [node.hostname == node-nuc4]
    expose:
      - 8008
    depends_on:
      - validator-4
    networks:
      - node_network
    command: sawtooth-rest-api --connect tcp://validator-4:4004 --bind rest-api-4:8008 -vv

  settings-tp-1:
    image: hyperledger/sawtooth-settings-tp:1.0
    deploy:
      placement:
        constraints: [node.hostname == node-nuc1]
    depends_on:
      - validator-1
    networks:
      - node_network
    command: settings-tp -v --connect tcp://validator-1:4004

  settings-tp-2:
    image: hyperledger/sawtooth-settings-tp:1.0
    deploy:
      placement:
        constraints: [node.hostname == node-nuc2]
    depends_on:
      - validator-2
    networks:
      - node_network
    command: settings-tp -v --connect tcp://validator-2:4004

  settings-tp-3:
    image: hyperledger/sawtooth-settings-tp:1.0
    deploy:
      placement:
        constraints: [node.hostname == node-nuc3]
    depends_on:
      - validator-3
    networks:
      - node_network
    command: settings-tp -v --connect tcp://validator-3:4004

  settings-tp-4:
    image: hyperledger/sawtooth-settings-tp:1.0
    deploy:
      placement:
        constraints: [node.hostname == node-nuc4]
    depends_on:
      - validator-4
    networks:
      - node_network
    command: settings-tp -v --connect tcp://validator-3:4004

  validator-1:
    image: hyperledger/sawtooth-validator:1.0
    deploy:
      placement:
        constraints: [node.hostname == node-nuc1]
    expose:
      - 4004
      - 8800
    networks:
      - node_network
    entrypoint: |
      bash -c "
        if [ ! -e /etc/sawtooth/keys/validator.priv ]; then \
          sawadm keygen; \
        fi && \
        if [ ! -e config-genesis.batch ]; then \
          sawset genesis -k /etc/sawtooth/keys/validator.priv -o config-genesis.batch; \
        fi && \
        if [ ! -e config.batch ]; then \
          sawset proposal create \
            -k /etc/sawtooth/keys/validator.priv \
            sawtooth.consensus.algorithm=poet \
            sawtooth.poet.report_public_key_pem=\"$$(cat /etc/sawtooth/simulator_rk_pub.pem)\" \
            sawtooth.poet.valid_enclave_measurements=$$(poet enclave measurement) \
            sawtooth.poet.valid_enclave_basenames=$$(poet enclave basename) \
            sawtooth.poet.initial_wait_time=15 \
            sawtooth.poet.target_wait_time=15 \
            sawtooth.publisher.max_batches_per_block=100 \
            -o config.batch; \
        fi && \
        if [ ! -e poet_genesis.batch ]; then \
          poet registration create -k /etc/sawtooth/keys/validator.priv -o poet_genesis.batch; \
        fi && \
        if [ ! -e /var/lib/sawtooth/genesis.batch ]; then \
          sawadm genesis config-genesis.batch config.batch poet_genesis.batch; \
        fi && \
        if [ ! -e /root/.sawtooth/keys/my_key.priv ]; then \
          sawtooth keygen my_key; \
        fi &&  \
        sawtooth-validator -v \
          --endpoint tcp://validator-1:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800 \
          --scheduler parallel \
          --peers tcp://validator-2:8800 \
          --peers tcp://validator-3:8800 \
          --peers tcp://validator-4:8800
      \"\""

  validator-2:
    image: hyperledger/sawtooth-validator:1.0
    deploy:
      placement:
        constraints: [node.hostname == node-nuc2]
    expose:
      - 4004
      - 8800
    networks:
      - node_network
    entrypoint: |
      bash -c "
        sawadm keygen && \
        sawtooth keygen my_key && \
        sawtooth-validator -v \
          --endpoint tcp://validator-2:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800 \
          --scheduler parallel \
          --peers tcp://validator-1:8800 \
          --peers tcp://validator-3:8800 \
          --peers tcp://validator-4:8800
      \"\""

  validator-3:
    image: hyperledger/sawtooth-validator:1.0
    deploy:
      placement:
        constraints: [node.hostname == node-nuc3]
    expose:
      - 4004
      - 8800
    networks:
      - node_network
    entrypoint: |
      bash -c "
        sawadm keygen && \
        sawtooth keygen my_key && \
        sawtooth-validator -v \
          --endpoint tcp://validator-3:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800 \
          --scheduler parallel \
          --peers tcp://validator-1:8800 \
          --peers tcp://validator-2:8800 \
          --peers tcp://validator-4:8800
      \"\""

  validator-4:
    image: hyperledger/sawtooth-validator:1.0
    deploy:
      placement:
        constraints: [node.hostname == node-nuc4]
    expose:
      - 4004
      - 5050
      - 8800
    networks:
      - node_network
    entrypoint: |
      bash -c "
        sawadm keygen && \
        sawtooth keygen my_key && \
        sawtooth-validator -v \
          --endpoint tcp://validator-4:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800 \
          --scheduler parallel \
          --peers tcp://validator-1:8800 \
          --peers tcp://validator-2:8800 \
          --peers tcp://validator-3:8800
      \"\""

  poet-validator-registry-tp-1:
    image: hyperledger/sawtooth-poet-validator-registry-tp:1.0
    deploy:
      placement:
        constraints: [node.hostname == node-nuc1]
    expose:
      - 4004
    depends_on:
      - validator-1
    networks:
      - node_network
    command: poet-validator-registry-tp -C tcp://validator-1:4004

  poet-validator-registry-tp-2:
    image: hyperledger/sawtooth-poet-validator-registry-tp:1.0
    deploy:
      placement:
        constraints: [node.hostname == node-nuc2]
    container_name: sawtooth-poet-validator-registry-tp-2
    expose:
      - 4004
    depends_on:
      - validator-2
    networks:
      - node_network
    command: poet-validator-registry-tp -C tcp://validator-2:4004

  poet-validator-registry-tp-3:
    image: hyperledger/sawtooth-poet-validator-registry-tp:1.0
    deploy:
      placement:
        constraints: [node.hostname == node-nuc3]
    expose:
      - 4004
    depends_on:
      - validator-3
    networks:
      - node_network
    command: poet-validator-registry-tp -C tcp://validator-3:4004

  poet-validator-registry-tp-4:
    image: hyperledger/sawtooth-poet-validator-registry-tp:1.0
    deploy:
      placement:
        constraints: [node.hostname == node-nuc4]
    expose:
      - 4004
    depends_on:
      - validator-4
    networks:
      - node_network
    command: poet-validator-registry-tp -C tcp://validator-4:4004

  intkey-tp-1:
    image: hyperledger/sawtooth-intkey-tp-python:1.0
    deploy:
      placement:
        constraints: [node.hostname == node-nuc1]
    networks:
      - node_network
    expose:
      - 4004
    command: intkey-tp-python -C tcp://validator-1:4004
    stop_signal: SIGKILL

  intkey-tp-2:
    image: hyperledger/sawtooth-intkey-tp-python:1.0
    deploy:
      placement:
        constraints: [node.hostname == node-nuc2]
    networks:
      - node_network
    expose:
      - 4004
    command: intkey-tp-python -C tcp://validator-2:4004
    stop_signal: SIGKILL

  intkey-tp-3:
    image: hyperledger/sawtooth-intkey-tp-python:1.0
    deploy:
      placement:
        constraints: [node.hostname == node-nuc3]
    networks:
      - node_network
    expose:
      - 4004
    command: intkey-tp-python -C tcp://validator-3:4004
    stop_signal: SIGKILL

  intkey-tp-4:
    image: hyperledger/sawtooth-intkey-tp-python:1.0
    deploy:
      placement:
        constraints: [node.hostname == node-nuc4]
    networks:
      - node_network
    expose:
      - 4004
    command: intkey-tp-python -C tcp://validator-4:4004
    stop_signal: SIGKILL
